name: Generate docs

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/**'
      - 'docs/**'
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      MIN_VERSION:
        description: "Minimum version (e.g., 0.12.0)"
        default: 0.1.0
      FILTER_VERSION:
        description: "Filter a specific version (e.g. main or 0.12.0)"
        default: main

env:
  BAZELISK_VERSION: 1.9.0
  MDBOOK_VERSION: 0.14.0

  GH_REPO: bazel-contrib/rules_foreign_cc
  MIN_VERSION: ${{ github.event.inputs.MIN_VERSION || '0.1.0' }}
  FILTER_VERSION: ${{ github.event.inputs.FILTER_VERSION || '' }}
  RELEASE_TAG_REGEX: ^\d+\.\d+\.\d+$

jobs:
  setup:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash --noprofile --norc -euo pipefail {0}

    steps:
      - name: get release tags that match $release_tag_regex
        id: get_release_tags
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASES_JSON="$(
            curl -s --fail-with-body \
              -H "Authorization: token $GH_TOKEN" \
              "https://api.github.com/repos/$GH_REPO/tags"
          )"

          RELEASES_JSON_FILTERED="$(echo "$RELEASES_JSON" |
            jq -c \
              --arg RELEASE_TAG_REGEX "$RELEASE_TAG_REGEX" \
              --arg FILTER_VERSION "$FILTER_VERSION" \
              --arg MIN_VERSION "$MIN_VERSION" '
              [ "main" ] +
              ([.[].name |
                 select(
                   (test($RELEASE_TAG_REGEX) and
                    (. | split(".") | map(tonumber) >= ($MIN_VERSION | split(".") | map(tonumber)))
                   ) and ($FILTER_VERSION == "" or . == $FILTER_VERSION)
                 )
              ])
              '
          )"
          echo "releases=$RELEASES_JSON_FILTERED"
          echo "releases=$RELEASES_JSON_FILTERED" >> "$GITHUB_OUTPUT"

    outputs:
      releases: ${{ steps.get_release_tags.outputs.releases || '[]' }}

  matrix-debug:
    runs-on: ubuntu-latest
    needs: setup

    defaults:
      run:
        shell: bash --noprofile --norc -euo pipefail {0}

    strategy:
      matrix:
        release: ${{ fromJson(needs.setup.outputs.releases) }}

    steps:
      - run: |-
          echo "RELEASE=${{ matrix.release }}"

  build:
    runs-on: ubuntu-latest
    needs: setup

    defaults:
      run:
        shell: bash --noprofile --norc -euo pipefail {0}

    strategy:
      matrix:
        ref: ${{ fromJson(needs.setup.outputs.releases) }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ matrix.ref }}

      - name: Patch old branch
        env:
          GH_REPO: ${{ github.repository }}
          PATCH_REF: "main"
          REF: ${{ matrix.ref }}
        run: |
          [[ "$REF" == "main" ]] && exit

          V_MAJOR="$(echo "$REF" | cut -d. -f1)"
          V_MINOR="$(echo "$REF" | cut -d. -f2)"

          [[ $V_MAJOR -gt 0 || $V_MINOR -gt 10 ]] && exit

          echo "Patching ref: $REF"

          PATCH=".github/docs-${REF}.patch"

          curl "https://raw.githubusercontent.com/$GH_REPO/$PATCH_REF/$PATCH" |
            git apply -

      - name: Install bazelisk
        run: |
          BAZELISK="bazelisk-linux-amd64"

          curl -LO \
            "https://github.com/bazelbuild/bazelisk/releases/download/v$BAZELISK_VERSION/$BAZELISK"

          mv "$BAZELISK" /usr/bin/bazel
          chmod +x /usr/bin/bazel

      - name: Install mdbook
        run: |
          MDBOOK="mdbook-v$MDBOOK_VERSION-x86_64-unknown-linux-gnu.tar.gz"

          curl -LO \
            "https://github.com/rust-lang/mdBook/releases/download/v$MDBOOK_VERSION/$MDBOOK"

          tar -xvf "$MDBOOK"
          mv mdbook /usr/bin/mdbook
          chmod +x /usr/bin/mdbook

      - name: bazel run //:generate_docs
        run: |
          bazel run //:generate_docs
          bazel clean
        working-directory: ${{ github.workspace }}/docs

      - name: mdbook build root
        run: mdbook build
        working-directory: ${{ github.workspace }}/docs/root
        if: ${{ matrix.ref == 'main' }}

      - name: mdbook build docs
        run: mdbook build
        working-directory: ${{ github.workspace }}/docs

      - name: Upload docs root
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.ref }}-root
          path: ${{ github.workspace }}/docs/root/book
          if-no-files-found: error
        if: ${{ github.event_name != 'pull_request' && matrix.ref == 'main' }}

      - name: Upload docs/book
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.ref }}
          path: ${{ github.workspace }}/docs/book
          if-no-files-found: error
        if: ${{ github.event_name != 'pull_request' }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name != 'pull_request' }}

    defaults:
      run:
        shell: bash --noprofile --norc -euo pipefail {0}

    steps:
      - name: Fetch artifacts (first root)
        uses: actions/download-artifact@v4
        with:
          name: main-root
          path: ${{ github.workspace }}/docs/book

      - name: Fetch artifacts (then others)
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/docs/pages

      - name: Install pages
        run: |
          mv \
            "${{ github.workspace }}/docs/pages/"* \
            "${{ github.workspace }}/docs/book/"

      - name: publish
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: docs
          publish_dir: ./docs/book
